sudo: required
services:
- docker
install:
- set -e
jobs:
  include:
  - stage: unit test
    language: go
    go:
    - 1.11.x
    env:
    - GO111MODULE=on
    go_import_path: github.com/buildpack/lifecycle
    script:
    - test -z "$(bin/format | tee >(cat >&2))"
    - go test -v
  - stage: build and push images
    env:
    - secure: "n07terjC1OL2iAhvYXhyOHFPRekLo3bpTckLkaf9N/IrdCBN6BjGfvZiX3b3Kd2D8sl501Jq8j4w3eSFZzp7dfN/peVFfD+hD3GOfKd6lanCgTGxWrBx+brJa6/3WxkMncY1hXrSqPjYEVFEOIhZRRG1Kzhkj+Fy4Xck83LF5m8DZA3MTiH3YijgmOYgw/zqAqcwS9v2nxsqQZm1OG1Av2BNW0ITF+Y0+oyZE7e2gpLU7sAEwCit6xIeDEKyOlSR+XHB0vkL7Cs7BCoOhwz/zZGjGIAAhbw64bnbuNMrVWmEzbKnp6N3OtGyPs0T5E1KlhaNmzXIkVgSSk4tU0wDBFIHuCM1+j3DI9aPu7PldruGsU6VwepnWuvKo0XFaihrQYBRFuw2U3/4Iw2OVjq2tHssYWATfA6hoPHJ678ZcH29WTnmTHLC2UbbaWaEoVFwUBK6BXuscuZIWhc61SZ3YVYEADAKvHJx65QFYx0LipCvVEpxxUsj4NxylA1XmD837Gr7BpuHJlfqr4l+5S9xFEF4I5c6Nn6HMjcCM0rN0bsYzOomyJAQ5wXquH1F+x60Jb6G/pPA9X+xS6fAki7R3tK4eORbFu/47hV+8zbwP2JCK16aCLXjZWSnTEP4XRZLQfM8rF/ypeJLIjOKKmTwR2Ucr9DpxQb9ZnHL+OwpBSU="
    - secure: "McMI5lalBxrsns6ZlekhwqQM0y8h2db3M49KppGVgCD3ShsKubQ14RLRT8tqs60f+UBVzEaMarqNXcSLcCiegH+gMbJazYGVog3vVt8m1AbQEQiSecuQ3GRW00jrjPOU82wJPmj3Xw/L4Pi9PKN+Fmol802gbZMQ69OhLAjiNic0jW+HJ4ZFxrD2ns4BmdMeBURGamZeyMsG3ISzgGfl+LoanV92N7de2bRl3tG88qquyrlVjOK5G+wmp+AK+LdeDly94kSrq1/Pgvpq5xIjK+5bdtn5cIEWaMPtfeKMU+UQjIWVWWU4BQ6ZdktKz6BumP1VGyP9JfNdH269e6UG/KM75QQEDAsv9Daq/oy2WEKMjs4LGv9OOsdzwPRrxOt+EWHwVOOXOXfhYMw5v250naqXAsZmO4PsUqmz8JsTuIVRttZX761d4f/JuPNpeE7GgxTc9D4VxziIl6ksDHrpRRQW4Hc4fznhBsUF7lyomCrwAWYSsZP4YBTYdykgKf0nNmf+iskzoIZfPuvzvWIim0K+ax5vp9B9ocd1mwQd5zPoAoYZRGhipw7d2hbkf8h8dakKdY8y/nBzomfXW1+4LFuuKSyELZg0z0rGu4t/jW6gHuILGCvPqBtCNIRTQSvLwk7Gzt/lKqZOv9P6Luh/UCI+mq+/lWyBy9zYUP0Swpc="
    script:
    - images/bin/build -v "0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker push "packs/base:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/build:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/run:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/util:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
