[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sclevine/spec"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/buildpack/packs"
  branch = "exporter"

[[override]]
	name = "github.com/google/go-containerregistry"
  revision = "11085b1805b9e9e6987278a5f61202d088e9b7f0"
